### ISSUE TITLE
Sorry not an bug here but please help

### ISSUE THREAD

**Issue by jakespeed1311** [Nullfati/test-git-rebase#2]
Hello,
Can you please give me the info what you have do to fix the problem
I havent found an other way to contakt you. Sorry for that.
You post this Issu with an Arduino DUE, and im am not so luky or nice programme i have search google and no fix was fund.   https://github.com/JoaoLopesF/SPFD5408/issues/18
greedings Jake
<<<<

I try compile the TFTPaint example for Arduino Due but have the errors.My Arduino IDE version: 1.8.5Arduino SAM Boards (32-bits ARM Cortex-M3): 1.6.11Errors list:In file included from C:\Users\Nullfati-note\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.11\variants\arduino_due_x/pins_arduino.h:20:0,
--

>>>>

**Comment by Nullfati** [comment]
Hello,
I maybe have saved modified library for DUE but for now, I don't have Arduino DUE and TFT display to test it.
Please, write me in Skype: live:andrey.manuna
I provide sources of modified lib.

**Comment by Nullfati** [comment]
Or my email: andrey.manuna@gmail.com

**Comment by badonj001** [comment]
I am having a problem with trying to upload my 3.5inch TFT Mega code to the Due. Seems to be in the variant.h having to do with invalid conversion of an unassigned character. I am still new to Arduino and am not really sure how to fix the compatibility issues from my Mega code. Any chance you have that code updated for due?

Any help appreciated, errors below - J:

In file included from C:\Users\badon\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.12\variants\arduino_due_x/pins_arduino.h:20:0,

                 from C:\Users\badon\OneDrive\Documents\Arduino\libraries\TouchScreen\TouchScreen.cpp:6:

C:\Users\badon\OneDrive\Documents\Arduino\libraries\TouchScreen\TouchScreen.cpp: In member function 'TSPoint TouchScreen::getPoint()':

variant.h:63:65: error: invalid conversion from 'Pio*' to 'uint8_t {aka unsigned char}' [-fpermissive]

 #define digitalPinToPort(P)        ( g_APinDescription[P].pPort )

                                                                 ^

C:\Users\badon\OneDrive\Documents\Arduino\libraries\TouchScreen\TouchScreen.cpp:57:21: note: in expansion of macro 'digitalPinToPort'

   uint8_t xp_port = digitalPinToPort(_xp);

                     ^

variant.h:63:65: error: invalid conversion from 'Pio*' to 'uint8_t {aka unsigned char}' [-fpermissive]

 #define digitalPinToPort(P)        ( g_APinDescription[P].pPort )

                                                                 ^

C:\Users\badon\OneDrive\Documents\Arduino\libraries\TouchScreen\TouchScreen.cpp:58:21: note: in expansion of macro 'digitalPinToPort'

   uint8_t yp_port = digitalPinToPort(_yp);

                     ^

variant.h:63:65: error: invalid conversion from 'Pio*' to 'uint8_t {aka unsigned char}' [-fpermissive]

 #define digitalPinToPort(P)        ( g_APinDescription[P].pPort )

                                                                 ^

C:\Users\badon\OneDrive\Documents\Arduino\libraries\TouchScreen\TouchScreen.cpp:59:21: note: in expansion of macro 'digitalPinToPort'

   uint8_t xm_port = digitalPinToPort(_xm);

                     ^

variant.h:63:65: error: invalid conversion from 'Pio*' to 'uint8_t {aka unsigned char}' [-fpermissive]

 #define digitalPinToPort(P)        ( g_APinDescription[P].pPort )

                                                                 ^

C:\Users\badon\OneDrive\Documents\Arduino\libraries\TouchScreen\TouchScreen.cpp:60:21: note: in expansion of macro 'digitalPinToPort'

   uint8_t ym_port = digitalPinToPort(_ym);

                     ^

variant.h:66:44: error: base operand of '->' is not a pointer

 #define portOutputRegister(port)   ( &(port->PIO_ODSR) )

                                            ^

C:\Users\badon\OneDrive\Documents\Arduino\libraries\TouchScreen\TouchScreen.cpp:73:4: note: in expansion of macro 'portOutputRegister'

   *portOutputRegister(yp_port) &= ~yp_pin;

    ^

variant.h:66:44: error: base operand of '->' is not a pointer

 #define portOutputRegister(port)   ( &(port->PIO_ODSR) )

                                            ^

C:\Users\badon\OneDrive\Documents\Arduino\libraries\TouchScreen\TouchScreen.cpp:74:4: note: in expansion of macro 'portOutputRegister'

   *portOutputRegister(ym_port) &= ~ym_pin;

    ^

variant.h:66:44: error: base operand of '->' is not a pointer

 #define portOutputRegister(port)   ( &(port->PIO_ODSR) )

                                            ^

C:\Users\badon\OneDrive\Documents\Arduino\libraries\TouchScreen\TouchScreen.cpp:82:4: note: in expansion of macro 'portOutputRegister'

   *portOutputRegister(xp_port) |= xp_pin;

    ^

variant.h:66:44: error: base operand of '->' is not a pointer

 #define portOutputRegister(port)   ( &(port->PIO_ODSR) )

                                            ^

C:\Users\badon\OneDrive\Documents\Arduino\libraries\TouchScreen\TouchScreen.cpp:83:4: note: in expansion of macro 'portOutputRegister'

   *portOutputRegister(xm_port) &= ~xm_pin;

    ^

variant.h:66:44: error: base operand of '->' is not a pointer

 #define portOutputRegister(port)   ( &(port->PIO_ODSR) )

                                            ^

C:\Users\badon\OneDrive\Documents\Arduino\libraries\TouchScreen\TouchScreen.cpp:98:5: note: in expansion of macro 'portOutputRegister'

    *portOutputRegister(xp_port) &= ~xp_pin;

     ^

variant.h:66:44: error: base operand of '->' is not a pointer

 #define portOutputRegister(port)   ( &(port->PIO_ODSR) )

                                            ^

C:\Users\badon\OneDrive\Documents\Arduino\libraries\TouchScreen\TouchScreen.cpp:102:5: note: in expansion of macro 'portOutputRegister'

    *portOutputRegister(yp_port) |= yp_pin;

     ^

variant.h:66:44: error: base operand of '->' is not a pointer

 #define portOutputRegister(port)   ( &(port->PIO_ODSR) )

                                            ^

C:\Users\badon\OneDrive\Documents\Arduino\libraries\TouchScreen\TouchScreen.cpp:121:5: note: in expansion of macro 'portOutputRegister'

    *portOutputRegister(xp_port) &= ~xp_pin;

     ^

variant.h:66:44: error: base operand of '->' is not a pointer

 #define portOutputRegister(port)   ( &(port->PIO_ODSR) )

                                            ^

C:\Users\badon\OneDrive\Documents\Arduino\libraries\TouchScreen\TouchScreen.cpp:125:5: note: in expansion of macro 'portOutputRegister'

    *portOutputRegister(ym_port) |= ym_pin;

     ^

variant.h:66:44: error: base operand of '->' is not a pointer

 #define portOutputRegister(port)   ( &(port->PIO_ODSR) )

Multiple libraries were found for "TouchScreen.h"
                                            ^

 Used: C:\Users\badon\OneDrive\Documents\Arduino\libraries\TouchScreen
 Not used: C:\Users\badon\OneDrive\Documents\Arduino\libraries\Adafruit_TouchScreen-master
C:\Users\badon\OneDrive\Documents\Arduino\libraries\TouchScreen\TouchScreen.cpp:129:5: note: in expansion of macro 'portOutputRegister'

    *portOutputRegister(yp_port) &= ~yp_pin;

     ^

exit status 1
invalid conversion from 'Pio*' to 'uint8_t {aka unsigned char}' [-fpermissive]

**Comment by Nullfati** [comment]
Look to this tree:
https://github.com/adafruit/TFTLCD-Library/tree/Due
